### PR TITLE
Update calendar.md

### PR DESCRIPTION
**Pull request by jonimec**

### CODE REVIEW

**Comment by yoavram** [comment]
Hi,
Which papers did you want to present?

**Comment by jonimec** [comment]
I think the polygenetic score

**Comment by yoavram** [comment]
The polygenic score topic is already done by @edanhauon, can you coordinate that you don't do the same papers? Maybe @edanhauon can present polygenic scores and you @jonimec can present the social genome papers?

**Comment by jonimec** [comment]
Ok i will talk with eden and see

**Pull request merged**
