### PR TITLE
Update calendar.md

### PR DESCRIPTION
**Pull request by guyhai**
this is the paper im interested in :
**Ginsberg, Jeremy, et al. “Detecting influenza epidemics using search engine query data.” Nature457.7232 (2009): 1012.**

### CODE REVIEW

**Comment by yoavram** [comment]
Hi that’s a paper for week 6 and you signed up for week 8. Right?

**Comment by guyhai** [comment]
yes, week 8 works better for me, I can also do a different Paper ofcourse.

**Comment by yoavram** [comment]
Week 8 we have a guest lecturer (same for week 6), so the topic of that week cannot be changed. There's also just one students presentation. I'd rather if you can choose by topic and not by timing, but of course I understand there are additional constraints.

**Comment by guyhai** [comment]
i changed it to week 6 with the paper  Ginsberg, Jeremy, et al. “Detecting
influenza epidemics using search engine query data.”
this is better?

**Comment by guyhai** [comment]
No problem I'll have a look at it again

**Comment by yoavram** [comment]
Canceled for #5

**Pull request closed without merging**
