### PR TITLE
Week 9 lecture registration

### PR DESCRIPTION
**Pull request by boaz85**

### CODE REVIEW

**Comment by yoavram** [comment]
Did you mean to sign for week 9 (as the Pr title says) or week 10 (as the edit says)?
I think you should do week 9 but it’s up to you.

**Comment by boaz85** [comment]
I meant week 9

‫בתאריך יום ב׳, 11 במרץ 2019 ב-21:01 מאת ‪Yoav Ram‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by yoavram** [comment]
Ok so I’ll wait for you to update the PR

**Comment by boaz85** [comment]
Fixed

**Comment by yoavram** [comment]
Great. What about meetings?

**Pull request merged**
